import type { TokenDefinition, TokenRegistry } from "../../types/index.js";

type TokenTreeNode = {
  children: Map<string, TokenTreeNode>;
  token?: TokenDefinition;
};

const RESERVED_WORDS = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "export",
  "extends",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "yield",
]);

const isValidIdentifier = (value: string) => {
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)) return false;
  return !RESERVED_WORDS.has(value);
};

const toPropertyKey = (key: string) => (isValidIdentifier(key) ? key : JSON.stringify(key));

const indentLines = (lines: string[], spaces: number) => {
  const prefix = " ".repeat(spaces);
  return lines.map((line) => (line.length ? `${prefix}${line}` : line));
};

const escapeJsDoc = (value: string) => value.replace(/\*\//g, "*\\/");

const buildTokenJsDocLines = (tokenName: string, token: TokenDefinition) => {
  const lines: string[] = [];
  if (token.description?.trim()) {
    lines.push(escapeJsDoc(token.description.trim()));
  }

  lines.push(`@token ${tokenName}`);

  if (token.category?.trim()) {
    lines.push(`@category ${escapeJsDoc(token.category.trim())}`);
  }

  const states = token.states ? Object.keys(token.states).sort() : [];
  if (states.length > 0) {
    lines.push(`@states ${states.join(", ")}`);
  }

  return ["/**", ...lines.map((line) => ` * ${line}`), " */"];
};

const buildTree = (registry: TokenRegistry): TokenTreeNode => {
  const root: TokenTreeNode = { children: new Map() };

  const entries = Object.entries(registry.tokens).sort(([a], [b]) => a.localeCompare(b));
  for (const [tokenName, token] of entries) {
    const segments = tokenName.split(".").filter(Boolean);
    if (segments.length === 0) continue;

    let node = root;
    for (const segment of segments) {
      let child = node.children.get(segment);
      if (!child) {
        child = { children: new Map() };
        node.children.set(segment, child);
      }
      node = child;
    }

    node.token = token;
  }

  return root;
};

const renderTreeTs = (node: TokenTreeNode, tokenNamePrefix: string): string[] => {
  const lines: string[] = ["{"];

  const keys = [...node.children.keys()].sort((a, b) => a.localeCompare(b));
  for (const key of keys) {
    const child = node.children.get(key);
    if (!child) continue;

    const fullTokenName = tokenNamePrefix ? `${tokenNamePrefix}.${key}` : key;
    const propKey = toPropertyKey(key);

    if (child.token && child.children.size === 0) {
      lines.push(...buildTokenJsDocLines(fullTokenName, child.token));
      lines.push(`${propKey}: "${fullTokenName}",`);
      continue;
    }

    const childLines = renderTreeTs(child, fullTokenName);
    lines.push(`${propKey}: ${childLines[0]}`);
    lines.push(...indentLines(childLines.slice(1), 2));
    lines[lines.length - 1] = `${lines[lines.length - 1]},`;
  }

  lines.push("}");
  return lines;
};

const renderTreeDts = (node: TokenTreeNode, tokenNamePrefix: string): string[] => {
  const lines: string[] = ["{"];

  const keys = [...node.children.keys()].sort((a, b) => a.localeCompare(b));
  for (const key of keys) {
    const child = node.children.get(key);
    if (!child) continue;

    const fullTokenName = tokenNamePrefix ? `${tokenNamePrefix}.${key}` : key;
    const propKey = toPropertyKey(key);

    if (child.token && child.children.size === 0) {
      lines.push(...buildTokenJsDocLines(fullTokenName, child.token));
      lines.push(`${propKey}: "${fullTokenName}";`);
      continue;
    }

    const childLines = renderTreeDts(child, fullTokenName);
    lines.push(`${propKey}: ${childLines[0]}`);
    lines.push(...indentLines(childLines.slice(1), 2));
    lines[lines.length - 1] = `${lines[lines.length - 1]};`;
  }

  lines.push("}");
  return lines;
};

export type GeneratedTokens = {
  tokenNames: string[];
  tokensTs: string;
  tokensDts: string;
};

/**
 * Generate `dist/palette/tokens.ts` and `dist/palette/tokens.d.ts` sources.
 *
 * Output is deterministic and derived from the token registry.
 */
export const generateTokenArtifacts = (registry: TokenRegistry): GeneratedTokens => {
  const tokenNames = Object.keys(registry.tokens).sort((a, b) => a.localeCompare(b));
  const tree = buildTree(registry);

  const tokensObject = renderTreeTs(tree, "");
  const tokensDtsObject = renderTreeDts(tree, "");

  const tokensTs = `/* This file is generated by palette-kit build (Phase 7). */\n\nexport const tokens = ${tokensObject.join(
    "\n",
  )} as const;\n\nexport const tokenNames = ${JSON.stringify(
    tokenNames,
    null,
    2,
  )} as const;\n\nexport type TokenName = (typeof tokenNames)[number];\n\nexport type ColorRole = TokenName;\n`;

  const tokensDts = `/* This file is generated by palette-kit build (Phase 7). */\n\nexport declare const tokens: ${tokensDtsObject.join(
    "\n",
  )};\n\nexport declare const tokenNames: readonly ${JSON.stringify(
    tokenNames,
    null,
    2,
  )};\n\nexport type TokenName = (typeof tokenNames)[number];\n\nexport type ColorRole = TokenName;\n`;

  return { tokenNames, tokensTs, tokensDts };
};
